- type: web
    name: hunters-worker-py
    env: docker
    dockerfilePath: ./worker-python/Dockerfile
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: TOKEN_ENCRYPTION_KEY
        sync: false
      - key: POLL_INTERVAL
        value: 15
